import {
  div,
  detached,
  input,
  group,
  section,
} from 'hexagon-js';

const fluidFactory = type => (cls = '') => detached(type).class(cls);

const label = fluidFactory('label');
const hr = fluidFactory('hr');
const vr = fluidFactory('vr');
const note = fluidFactory('note');

const radio = (checked, disabled) => input().attr('type', 'radio')
  .class('hx-input-radio')
  .prop('checked', !!checked)
  .attr('disabled', disabled ? 'disabled' : undefined);

const invalidRadio = value => radio()
  .attr('value', value)
  .attr('name', 'g1')
  .attr('required', true);

export default () => div()
  .add(group({ compact: true, horizontal: true })
    .add(section()
      .add(div('hx-header-medium').text('Valid State'))
      .add(hr())
      .add(div('hx-form hx-flag-form')
        .add(div('hx-form-group')
          .add(label('hx-form-label').text('Label'))
          .add(div('hx-form-item')
            .add(radio())
            .add(label('hx-form-label').text('Radio Button')))
          .add(div('hx-form-item')
            .add(radio(true))
            .add(label('hx-form-label').text('Radio Button'))))))
    .add(vr())
    .add(section()
      .add(div('hx-header-medium').text('Invalid State'))
      .add(hr())
      .add(div('hx-form hx-flag-form')
        .add(div('hx-form-group')
          .add(label('hx-form-label').text('Label'))
          .add(div('hx-form-item')
            .add(invalidRadio('n1'))
            .add(label('hx-form-label').text('Radio Button')))
          .add(div('hx-form-item')
            .add(invalidRadio('n2'))
            .add(label('hx-form-label').text('Radio Button')))
          .add(div('hx-form-message').text('Warning message will be here'))))))
  .add(hr())
  .add(div('hx-header-medium').text('Variations'))
  .add(note().text('Radio buttons, one option disabled'))
  .add(div('hx-form hx-flag-form')
    .add(div('hx-form-group')
      .add(label('hx-form-label').text('Label'))
      .add(div('hx-form-item')
        .add(radio())
        .add(label('hx-form-label').text('Radio Button')))
      .add(div('hx-form-item')
        .add(radio())
        .add(label('hx-form-label').text('Radio Button')))
      .add(div('hx-form-item')
        .add(radio())
        .add(label('hx-form-label').text('Radio Button')))
      .add(div('hx-form-item')
        .add(radio(false, true))
        .add(label('hx-form-label').text('Radio Button (Not available)')))))
  .add(hr())
  .add(group({ compact: true, horizontal: true })
    .add(section()
      .add(div('do'))
      .add(div('hx-form hx-flag-form')
        .add(div('hx-form-group')
          .add(label('hx-form-label').text('Label'))
          .add(div('hx-form-item')
            .add(radio())
            .add(label('hx-form-label').text('Yes')))
          .add(div('hx-form-item')
            .add(radio(true))
            .add(label('hx-form-label').text('No'))))))
    .add(section()
      .add(div('dont'))
      .add(div('hx-form hx-flag-form')
        .add(div('hx-form-group')
          .add(label('hx-form-label').text('Label'))
          .add(div('hx-form-item')
            .add(radio())
            .add(label('hx-form-label').text('Yes')))
          .add(div('hx-form-item')
            .add(radio(true))
            .add(label('hx-form-label').text('No')))
          .add(div('hx-form-item')
            .add(radio())
            .add(label('hx-form-label').text('Yes, but I need more info')))
          .add(div('hx-form-item')
            .add(radio())
            .add(label('hx-form-label').text('Yes, but it can be no too')))
          .add(div('hx-form-item')
            .add(radio())
            .add(label('hx-form-label').text('Yes, if certain things happen')))
          .add(div('hx-form-item')
            .add(radio())
            .add(label('hx-form-label').text('Mostly not')))
          .add(div('hx-form-item')
            .add(radio())
            .add(label('hx-form-label').text('No, but I may change my mind')))
          .add(div('hx-form-item')
            .add(radio())
            .add(label('hx-form-label').text('Maybe')))))));
