import {
  div,
  detached,
  input,
  group,
  section,
} from 'hexagon-js';

const fluidFactory = type => (cls = '') => detached(type).class(cls);

const label = fluidFactory('label');
const hr = fluidFactory('hr');
const vr = fluidFactory('vr');
const note = fluidFactory('note');

const radio = (name, value, checked, disabled) => input().attr('type', 'radio')
  .class('hx-input-radio')
  .attr('name', name)
  .attr('value', value)
  .attr('id', value)
  .prop('checked', !!checked)
  .attr('disabled', disabled ? 'disabled' : undefined);

const invalidRadio = (name, value) => radio(name, value)
  .attr('required', true);

export default () => div()
  .add(group({ compact: true, horizontal: true })
    .add(section()
      .add(div('hx-header-medium').text('Valid State'))
      .add(hr())
      .add(div('hx-form hx-flag-form')
        .add(div('hx-form-group')
          .add(label('hx-form-label').text('Label'))
          .add(div('hx-form-item')
            .add(radio('a', 'a1'))
            .add(label('hx-form-label').attr('for', 'a1').text('Radio Button')))
          .add(div('hx-form-item')
            .add(radio('a', 'a2', true))
            .add(label('hx-form-label').attr('for', 'a2').text('Radio Button'))))))
    .add(vr())
    .add(section()
      .add(div('hx-header-medium').text('Invalid State'))
      .add(hr())
      .add(div('hx-form hx-flag-form')
        .add(div('hx-form-group')
          .add(label('hx-form-label').text('Label'))
          .add(div('hx-form-item')
            .add(invalidRadio('n', 'n1'))
            .add(label('hx-form-label').attr('for', 'n1').text('Radio Button')))
          .add(div('hx-form-item')
            .add(invalidRadio('n', 'n2'))
            .add(label('hx-form-label').attr('for', 'n2').text('Radio Button')))
          .add(div('hx-form-message').text('Warning message will be here'))))))
  .add(hr())
  .add(div('hx-header-medium').text('Variations'))
  .add(note().text('Radio buttons, one option disabled'))
  .add(div('hx-form hx-flag-form')
    .add(div('hx-form-group')
      .add(label('hx-form-label').text('Label'))
      .add(div('hx-form-item')
        .add(radio('c', 'c1'))
        .add(label('hx-form-label').attr('for', 'c1').text('Radio Button')))
      .add(div('hx-form-item')
        .add(radio('c', 'c2'))
        .add(label('hx-form-label').attr('for', 'c2').text('Radio Button')))
      .add(div('hx-form-item')
        .add(radio('c', 'c3'))
        .add(label('hx-form-label').attr('for', 'c3').text('Radio Button')))
      .add(div('hx-form-item')
        .add(radio('c', 'c4', false, true))
        .add(label('hx-form-label').attr('for', 'c4').text('Radio Button (Not available)')))))
  .add(hr())
  .add(group({ compact: true, horizontal: true })
    .add(section()
      .add(div('do'))
      .add(div('hx-form hx-flag-form')
        .add(div('hx-form-group')
          .add(label('hx-form-label').text('Label'))
          .add(div('hx-form-item')
            .add(radio('d', 'd1'))
            .add(label('hx-form-label').attr('for', 'd1').text('Yes')))
          .add(div('hx-form-item')
            .add(radio('d', 'd2', true))
            .add(label('hx-form-label').attr('for', 'd2').text('No'))))))
    .add(section()
      .add(div('dont'))
      .add(div('hx-form hx-flag-form')
        .add(div('hx-form-group')
          .add(label('hx-form-label').text('Label'))
          .add(div('hx-form-item')
            .add(radio('e', 'e1'))
            .add(label('hx-form-label').attr('for', 'e1').text('Yes')))
          .add(div('hx-form-item')
            .add(radio('e', 'e2', true))
            .add(label('hx-form-label').attr('for', 'e2').text('No')))
          .add(div('hx-form-item')
            .add(radio('e', 'e3'))
            .add(label('hx-form-label').attr('for', 'e3').text('Yes, but I need more info')))
          .add(div('hx-form-item')
            .add(radio('e', 'e4'))
            .add(label('hx-form-label').attr('for', 'e4').text('Yes, but it can be no too')))
          .add(div('hx-form-item')
            .add(radio('e', 'e5'))
            .add(label('hx-form-label').attr('for', 'e5').text('Yes, if certain things happen')))
          .add(div('hx-form-item')
            .add(radio('e', 'e6'))
            .add(label('hx-form-label').attr('for', 'e6').text('Mostly not')))
          .add(div('hx-form-item')
            .add(radio('e', 'e7'))
            .add(label('hx-form-label').attr('for', 'e7').text('No, but I may change my mind')))
          .add(div('hx-form-item')
            .add(radio('e', 'e8'))
            .add(label('hx-form-label').attr('for', 'e8').text('Maybe')))))));
