#!/bin/bash

./module.sh animate "Animate"
./module.sh autocomplete "Autocomplete"
./module.sh autocomplete-picker "Autocomplete Picker"
./module.sh base "Base"
./module.sh button "Button"
./module.sh button-group "Button Group"
./module.sh card "Card"
./module.sh click-detector "Click Detector"
./module.sh collapsible "Collapsible"
./module.sh color "Color"
./module.sh color-picker "Color Picker"
./module.sh color-scale "Color Scale"
./module.sh component "Component"
./module.sh crumbtrail "Crumbtrail"
./module.sh dashboard "Dashboard"
./module.sh data-table "Data Table"
./module.sh date-picker "Date Picker"
./module.sh date-time-picker "Date Time Picker"
./module.sh drag-container "Drag Container"
./module.sh drawing "Drawing"
./module.sh dropdown "Dropdown"
./module.sh error-pages "Error Pages"
./module.sh event-emitter "Event Emitter"
./module.sh extended-table "Extended Table"
./module.sh fast-click "Fast Click"
./module.sh file-input "File Input"
./module.sh filter "Filter"
./module.sh fluid "Fluid"
./module.sh form "Form"
./module.sh form-builder "Form Builder"
./module.sh format "Format"
./module.sh inline-editable "Inline Editable"
./module.sh inline-picker "Inline Picker"
./module.sh inline-select "Inline Select"
./module.sh input-group "Input Group"
./module.sh interpolate "Interpolate"
./module.sh label "Label"
./module.sh layout "Layout"
./module.sh list "List"
./module.sh logo "Logo"
./module.sh map "Map"
./module.sh menu "Menu"
./module.sh meter "Meter"
./module.sh modal "Modal"
./module.sh morph-section "Morph Section"
./module.sh morphs "Morphs"
./module.sh notice "Notice"
./module.sh notify "Notify"
./module.sh number-picker "Number Picker"
./module.sh paginator "Paginator"
./module.sh palette "Palette"
./module.sh picker "Picker"
./module.sh pivot-table "Pivot Table"
./module.sh plot "Plot"
./module.sh pointer-events "Pointer Events"
./module.sh preferences "Preferences"
./module.sh progress-bar "Progress Bar"
./module.sh request "Request"
./module.sh resize-events "Resize Events"
./module.sh search-dom "Search Dom"
./module.sh select "Select"
./module.sh selection "Selection"
./module.sh set "Set"
./module.sh side-collapsible "Side Collapsible"
./module.sh sidebar "Sidebar"
./module.sh slider "Slider"
./module.sh sort "Sort"
./module.sh spinner "Spinner"
./module.sh sticky-table-headers "Sticky Table Headers"
./module.sh table "Table"
./module.sh tabs "Tabs"
./module.sh tag-input "Tag Input"
./module.sh time-picker "Time Picker"
./module.sh time-slider "Time Slider"
./module.sh titlebar "Titlebar"
./module.sh toggle "Toggle"
./module.sh toggle-button "Toggle Button"
./module.sh transition "Transition"
./module.sh tree "Tree"
./module.sh user-facing-text "User Facing Text"
./module.sh util "Util"
./module.sh view "View"
