const defaultLocaleObjects = [
  { value: 'af', full: 'Afrikaans' },
  { value: 'sq', full: 'Albanian' },
  { value: 'ar', full: 'Arabic' },
  { value: 'ar-MA', full: 'Arabic (Morocco)' },
  { value: 'ar-SA', full: 'Arabic (Saudi Arabia)' },
  { value: 'ar-TN', full: 'Arabic (Tunisia)' },
  { value: 'hy-AM', full: 'Armenian' },
  { value: 'az', full: 'Azerbaijani' },
  { value: 'id', full: 'Bahasa Indonesia' },
  { value: 'ms-MY', full: 'Bahasa Malayu' },
  { value: 'eu', full: 'Basque' },
  { value: 'be', full: 'Belarusian' },
  { value: 'bn', full: 'Bengali' },
  { value: 'bs', full: 'Bosnian' },
  { value: 'br', full: 'Breton' },
  { value: 'bg', full: 'Bulgarian' },
  { value: 'my', full: 'Burmese' },
  { value: 'ca', full: 'Catalan' },
  { value: 'zh-CN', full: 'Chinese' },
  { value: 'zh-TW', full: 'Chinese (Traditional)' },
  { value: 'cv', full: 'Chuvash' },
  { value: 'hr', full: 'Croatian' },
  { value: 'cs', full: 'Czech' },
  { value: 'da', full: 'Danish' },
  { value: 'nl', full: 'Dutch' },
  { value: 'en', full: 'English' },
  { value: 'en-US', full: 'English (US)' },
  { value: 'en-AU', full: 'English (Australia)' },
  { value: 'en-CA', full: 'English (Canada)' },
  { value: 'en-GB', full: 'English (UK) ' },
  { value: 'eo', full: 'Esperanto' },
  { value: 'et', full: 'Estonian' },
  { value: 'fo', full: 'Farose' },
  { value: 'fi', full: 'Finnish' },
  { value: 'fr', full: 'French' },
  { value: 'fr-CA', full: 'French (Canada)' },
  { value: 'fy', full: 'Frisian' },
  { value: 'gl', full: 'Galician' },
  { value: 'ka', full: 'Georgian' },
  { value: 'de', full: 'German' },
  { value: 'de-AT', full: 'German (Austria)' },
  { value: 'el', full: 'Greek' },
  { value: 'he', full: 'Hebrew' },
  { value: 'hi', full: 'Hindi' },
  { value: 'hu', full: 'Hungarian' },
  { value: 'is', full: 'Icelandic' },
  { value: 'it', full: 'Italian' },
  { value: 'ja', full: 'Japanese' },
  { value: 'km', full: 'Khmer (Cambodia)' },
  { value: 'ko', full: 'Korean' },
  { value: 'lv', full: 'Latvian' },
  { value: 'lt', full: 'Lithuanian' },
  { value: 'lb', full: 'Luxembourgish' },
  { value: 'mk', full: 'Macedonian' },
  { value: 'ml', full: 'Malayalam' },
  { value: 'mr', full: 'Marathi' },
  { value: 'ne', full: 'Nepalese' },
  { value: 'nb', full: 'Norwegian' },
  { value: 'nn', full: 'Norwegian Nynorsk' },
  { value: 'fa', full: 'Persian' },
  { value: 'pl', full: 'Polish' },
  { value: 'pt', full: 'Portuguese' },
  { value: 'pt-BR', full: 'Portuguese (Brazil)' },
  { value: 'ro', full: 'Romanian' },
  { value: 'ru', full: 'Russian' },
  { value: 'sr', full: 'Serbian' },
  { value: 'sr-CYRL', full: 'Serbian Cyrillic' },
  { value: 'sk', full: 'Slovak' },
  { value: 'sl', full: 'Slovenian' },
  { value: 'es', full: 'Spanish' },
  { value: 'sv', full: 'Swedish' },
  { value: 'tl-PH', full: 'Tagalog (Filipino)' },
  { value: 'tzm', full: 'Tamaziɣt' },
  { value: 'tzm-LATN', full: 'Tamaziɣt Latin' },
  { value: 'ta', full: 'Tamil' },
  { value: 'th', full: 'Thai' },
  { value: 'bo', full: 'Tibetan' },
  { value: 'tr', full: 'Turkish' },
  { value: 'uk', full: 'Ukrainian' },
  { value: 'uz', full: 'Uzbek' },
  { value: 'vi', full: 'Vietnamese' },
  { value: 'cy', full: 'Welsh' },
];

const defaultTimezoneList = [
  'UTC-12:00',
  'UTC-11:00',
  'UTC-10:00',
  'UTC-09:30',
  'UTC-09:00',
  'UTC-08:00',
  'UTC-07:00',
  'UTC-06:00',
  'UTC-05:00',
  'UTC-04:30',
  'UTC-04:00',
  'UTC-03:30',
  'UTC-03:00',
  'UTC-02:00',
  'UTC-01:00',
  'UTC+00:00',
  'UTC+01:00',
  'UTC+02:00',
  'UTC+03:00',
  'UTC+03:30',
  'UTC+04:00',
  'UTC+04:30',
  'UTC+05:00',
  'UTC+05:30',
  'UTC+05:45',
  'UTC+06:00',
  'UTC+06:30',
  'UTC+07:00',
  'UTC+08:00',
  'UTC+08:30',
  'UTC+08:45',
  'UTC+09:00',
  'UTC+09:30',
  'UTC+10:00',
  'UTC+10:30',
  'UTC+11:00',
  'UTC+12:00',
  'UTC+12:45',
  'UTC+13:00',
  'UTC+14:00',
];

const defaultLocaleList = defaultLocaleObjects.map(({ value }) => value);

export {
  defaultLocaleList,
  defaultLocaleObjects,
  defaultTimezoneList,
};
