import { detached, div, button, span } from 'hexagon-js'

export default () => {
  return detached('form').class('hx-form')
    .add(div()
      .add(detached('label').text('Text'))
      .add(detached('input').attr('type', 'text')))
    .add(div()
      .add(detached('label').text('Email'))
      .add(detached('input').attr('type', 'email')))
    .add(div()
      .add(detached('label').text('Number'))
      .add(detached('input').attr('type', 'number')))
    .add(div()
      .add(detached('label').text('Url'))
      .add(detached('input').attr('type', 'url')))
    .add(div()
      .add(detached('label').text('Radio'))
      .add(div().attr('id', 'group-1')
        .add(div()
          .add(detached('input').attr('id', 'radio1').attr('type', 'radio').attr('value', 'One').attr('name', 'group-1'))
          .add(detached('label').attr('for', 'radio1').text('One')))
        .add(div()
          .add(detached('input').attr('id', 'radio2').attr('type', 'radio').attr('value', 'Two').attr('name', 'group-1'))
          .add(detached('label').attr('for', 'radio2').text('Two')))
        .add(div()
          .add(detached('input').attr('id', 'radio3').attr('type', 'radio').attr('value', 'Three').attr('name', 'group-1'))
          .add(detached('label').attr('for', 'radio3').text('Three')))))
    .add(div()
      .add(detached('label').attr('for', 'checkbox1').text('Checkbox'))
      .add(detached('input').attr('id', 'checkbox1').attr('type', 'checkbox')))
    // .add(div()
    //   .add(detached('label').text('Tag Input'))
    //   .add(div()
    //     .add(tagInput())))
    .add(button('hx-btn hx-positive').attr('type', 'submit')
      .add(detached('i').class('fa fa-paper-plane'))
      .add(span().text(' Submit')))
}
